version: '3'

services:
  
  front:
    build: ./juicios
    ports:
      - 4200:80
    volumes:
      - ./juicios:/front
      - /front/node_modules
    networks:
      - service    
    links:
      - api
        
  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/flask
    environment:
      FLASK_ENV: development
    networks:
      - legacy
      - service
    links:
      - db-server
      - tika

  db-server:
    image: mysql
    networks:
      - legacy  
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: juicios
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  tika:
    image: apache/tika
    ports:
      - 9998:9998
    networks:
      - legacy

networks:
  legacy:
  service:
      