version: '3'

services:

  front:
    build: ./juicios
    ports:
      - 4200:80
    volumes:
      - ./juicios:/front
      - /front/node_modules 
    links:
      - api

  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/flask
    environment:
      FLASK_ENV: development
    links:
      - db
      - tika

  db:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: juicios
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  tika:
    image: apache/tika
    ports:
      - 9998:9998
