version: '3'

services:
  
  tika:
    image: apache/tika 
    ports: '9998':9998'

  api:
    build: ./
    ports:
      - '5000:5000'
    volumes:
        - ./:/flask
    environment:
        FLASK_ENV: development
