version: '3'
services:
  tika:
    image: apache/tika
    ports:
      - '9998:9998'

  db-server:
    image: mysql
    ports:
      - '3306:3306'

  api:
    build: ./
    ports:
      - '5000:5000'
    volumes:
        - ./:/flask
    environment:
        FLASK_ENV: development
