version: '3'
services:

  tika:
    image: apache/tika
    ports:
      - 9998:9998

  db-server:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: juicios
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
        - ./:/flask
    environment:
        FLASK_ENV: development

  front:
    build: ./juicios
    ports:
      - 4200:4200
    volumes:
      - ./juicios:/front
      - /front/node_modules
